# See https://duncanleung.com/eslint-mixed-javascript-typescript-files-codebase/
env:
  es6: true
  jest: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
ignorePatterns: src/**/*.js
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - eslint-plugin-tsdoc
  - googleappsscript
  # Disable rules that conflict with Prettier
  # Prettier must be last to override other configs
  - "prettier"
root: true
rules:
  tsdoc/syntax: warn
