name: Node.js CI

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: ls -al build/gas/lib build/gas/examples
      - uses: daikikatsuragawa/clasp-action@v1.1.0
        if: github.ref == 'refs/heads/v2'
        with:
          accessToken: ${{ secrets.CLASP_ACCESS_TOKEN }}
          idToken: ${{ secrets.CLASP_ID_TOKEN }}
          refreshToken: ${{ secrets.CLASP_REFRESH_TOKEN }}
          clientId: ${{ secrets.CLASP_CLIENT_ID }}
          clientSecret: ${{ secrets.CLASP_CLIENT_SECRET }}
          scriptId: ${{ secrets.CLASP_SCRIPT_ID }}
          command: "deploy"
          rootDir: "build/gas/lib"
          description: "Development Snapshot"
          deployId: ${{ secrets.CLASP_DEPLOYMENT_ID_LIB_DEV }}
      - uses: daikikatsuragawa/clasp-action@v1.1.0
        if: github.ref == 'refs/heads/v2'
        with:
          accessToken: ${{ secrets.CLASP_ACCESS_TOKEN }}
          idToken: ${{ secrets.CLASP_ID_TOKEN }}
          refreshToken: ${{ secrets.CLASP_REFRESH_TOKEN }}
          clientId: ${{ secrets.CLASP_CLIENT_ID }}
          clientSecret: ${{ secrets.CLASP_CLIENT_SECRET }}
          scriptId: ${{ secrets.CLASP_SCRIPT_ID }}
          command: "deploy"
          rootDir: "build/gas/examples"
          description: "Development Snapshot"
          deployId: ${{ secrets.CLASP_DEPLOYMENT_ID_EXAMPLES_DEV }}
