name: CI

on:
  push:
    branches:
      - beta
      - main
  workflow_dispatch:

env:
  CLASP_ACCESS_TOKEN: ${{secrets.CLASP_ACCESS_TOKEN}}
  CLASP_CLIENT_ID: ${{secrets.CLASP_CLIENT_ID}}
  CLASP_CLIENT_SECRET: ${{secrets.CLASP_CLIENT_SECRET}}
  CLASP_EXAMPLES_DEPLOYMENT_ID_BETA: ${{secrets.CLASP_EXAMPLES_DEPLOYMENT_ID_BETA}}
  CLASP_EXAMPLES_DEPLOYMENT_ID_MAIN: ${{secrets.CLASP_EXAMPLES_DEPLOYMENT_ID_MAIN}}
  CLASP_EXAMPLES_SCRIPT_ID_BETA: ${{secrets.CLASP_EXAMPLES_SCRIPT_ID_BETA}}
  CLASP_EXAMPLES_SCRIPT_ID_MAIN: ${{secrets.CLASP_EXAMPLES_SCRIPT_ID_MAIN}}
  CLASP_ID_TOKEN: ${{secrets.CLASP_ID_TOKEN}}
  CLASP_LIB_DEPLOYMENT_ID_BETA: ${{secrets.CLASP_LIB_DEPLOYMENT_ID_BETA}}
  CLASP_LIB_DEPLOYMENT_ID_MAIN: ${{secrets.CLASP_LIB_DEPLOYMENT_ID_MAIN}}
  CLASP_LIB_SCRIPT_ID_BETA: ${{secrets.CLASP_LIB_SCRIPT_ID_BETA}}
  CLASP_LIB_SCRIPT_ID_MAIN: ${{secrets.CLASP_LIB_SCRIPT_ID_MAIN}}
  CLASP_REFRESH_TOKEN: ${{secrets.CLASP_REFRESH_TOKEN}}
  GCLOUD_PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
  GCLOUD_PROJECT_NR: ${{secrets.GCLOUD_PROJECT_NR}}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: nodejs
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - id: build
        name: Build
        run: npm run ci
      - id: coverage
        name: Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2
      - id: release
        name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx run release:perform
      - id: push
        name: Push
        run: npm run push
      - id: deploy
        name: Deploy
        run: npm run deploy
