name: CI

on:
  # Runs on pushes targeting certain branches
  push:
    branches:
      - $default-branch # main
      - beta
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      releaseVersion: ${{ steps.release.outputs.releaseVersion }}
    environment:
      name: ${{ github.ref_name }}
    env:
      CLASP_ACCESS_TOKEN: ${{secrets.CLASP_ACCESS_TOKEN}}
      CLASP_CLIENT_ID: ${{secrets.CLASP_CLIENT_ID}}
      CLASP_CLIENT_SECRET: ${{secrets.CLASP_CLIENT_SECRET}}
      CLASP_EXAMPLES_DEPLOYMENT_ID: ${{secrets.CLASP_EXAMPLES_DEPLOYMENT_ID}}
      CLASP_EXAMPLES_SCRIPT_ID: ${{secrets.CLASP_EXAMPLES_SCRIPT_ID}}
      CLASP_ID_TOKEN: ${{secrets.CLASP_ID_TOKEN}}
      CLASP_LIB_DEPLOYMENT_ID: ${{secrets.CLASP_LIB_DEPLOYMENT_ID}}
      CLASP_LIB_SCRIPT_ID: ${{secrets.CLASP_LIB_SCRIPT_ID}}
      CLASP_REFRESH_TOKEN: ${{secrets.CLASP_REFRESH_TOKEN}}
      GCLOUD_PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
      GCLOUD_PROJECT_NR: ${{secrets.GCLOUD_PROJECT_NR}}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: nodejs
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - id: build
        name: Build
        run: npm run ci
      - id: coverage
        name: Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2
      - id: push-lib
        name: Push Lib
        run: npm run push
      - id: release
        name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release:perform && npm run release:releaseVersion | grep -E '^releaseVersion=' >> "$GITHUB_OUTPUT" || true
      - id: deploy-lib
        if: ${{ steps.release.outputs.releaseVersion }}
        name: Deploy Lib
        run: npm run deploy
      - id: setup-pages
        if: ${{ steps.release.outputs.releaseVersion }}
        name: Setup Pages
        uses: actions/configure-pages@v3
      - id: upload-pages
        if: ${{ steps.release.outputs.releaseVersion }}
        name: Upload Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: "build/docs"
      - name: Deploy Pages
        if: ${{ steps.release.outputs.releaseVersion }}
        id: deploy-pages
        uses: actions/deploy-pages@v2
